#copy to /etc/ly/config.ini


# The active animation
animation = none

# format string for clock in top right corner (see strftime specification)
clock = %Y-%m-%d %H:%M:%S

# enable/disable big clock
bigclock = true

# The character used to mask the password
asterisk = *

# Erase password input on failure
blank_password = true

#The `fg` and `bg` color settings take a digit 0-8 corresponding to:
#define TB_DEFAULT 0x00
#define TB_BLACK   0x01
#define TB_RED     0x02
#define TB_GREEN   0x03
#define TB_YELLOW  0x04
#define TB_BLUE    0x05
#define TB_MAGENTA 0x06
#define TB_CYAN    0x07
#define TB_WHITE   0x08

# Background color id
bg = 0

# Foreground color id
fg = 9

# Blank main box background
# Setting to false will make it transparent
blank_box = true

# Remove main box borders
hide_borders = false

# Main box margins
margin_box_h = 6
margin_box_v = 3

# Input boxes length
input_len = 40

# Max input sizes
max_desktop_len = 100
max_login_len = 255
max_password_len = 255

# F1/F2 commands
hide_key_hints = false

load = true

# Enable autologin

auto_login_user=user
auto_login_session=mango
auto_login_service = ly-autologin
