#!/usr/bin/env python3
# timezone-list.py — prints all timezone entries for the QS launcher.
# Output format per line:
#   DISPLAY  [ABBR]  →  IANA/Zone  @@OFFSET_SECONDS
# where OFFSET_SECONDS is the current UTC offset (including DST) in seconds.

import datetime, zoneinfo, pathlib, sys

ALIASES = {
    # --- Countries ---
    "Afghanistan":             "Asia/Kabul",
    "Albania":                 "Europe/Tirane",
    "Algeria":                 "Africa/Algiers",
    "Angola":                  "Africa/Luanda",
    "Argentina":               "America/Argentina/Buenos_Aires",
    "Armenia":                 "Asia/Yerevan",
    "Australia":               "Australia/Sydney",
    "Austria":                 "Europe/Vienna",
    "Azerbaijan":              "Asia/Baku",
    "Bahrain":                 "Asia/Bahrain",
    "Bangladesh":              "Asia/Dhaka",
    "Belarus":                 "Europe/Minsk",
    "Belgium":                 "Europe/Brussels",
    "Bolivia":                 "America/La_Paz",
    "Bosnia":                  "Europe/Sarajevo",
    "Brazil":                  "America/Sao_Paulo",
    "Bulgaria":                "Europe/Sofia",
    "Cambodia":                "Asia/Phnom_Penh",
    "Canada":                  "America/Toronto",
    "Chile":                   "America/Santiago",
    "China":                   "Asia/Shanghai",
    "Colombia":                "America/Bogota",
    "Croatia":                 "Europe/Zagreb",
    "Cuba":                    "America/Havana",
    "Czech Republic":          "Europe/Prague",
    "Czechia":                 "Europe/Prague",
    "Denmark":                 "Europe/Copenhagen",
    "Ecuador":                 "America/Guayaquil",
    "Egypt":                   "Africa/Cairo",
    "Estonia":                 "Europe/Tallinn",
    "Ethiopia":                "Africa/Addis_Ababa",
    "Finland":                 "Europe/Helsinki",
    "France":                  "Europe/Paris",
    "Georgia":                 "Asia/Tbilisi",
    "Germany":                 "Europe/Berlin",
    "Ghana":                   "Africa/Accra",
    "Greece":                  "Europe/Athens",
    "Guatemala":               "America/Guatemala",
    "Hungary":                 "Europe/Budapest",
    "Iceland":                 "Atlantic/Reykjavik",
    "India":                   "Asia/Kolkata",
    "Indonesia":               "Asia/Jakarta",
    "Iran":                    "Asia/Tehran",
    "Iraq":                    "Asia/Baghdad",
    "Ireland":                 "Europe/Dublin",
    "Israel":                  "Asia/Jerusalem",
    "Italy":                   "Europe/Rome",
    "Jamaica":                 "America/Jamaica",
    "Japan":                   "Asia/Tokyo",
    "Jordan":                  "Asia/Amman",
    "Kazakhstan":              "Asia/Almaty",
    "Kenya":                   "Africa/Nairobi",
    "Kuwait":                  "Asia/Kuwait",
    "Kyrgyzstan":              "Asia/Bishkek",
    "Laos":                    "Asia/Vientiane",
    "Latvia":                  "Europe/Riga",
    "Lebanon":                 "Asia/Beirut",
    "Libya":                   "Africa/Tripoli",
    "Lithuania":               "Europe/Vilnius",
    "Luxembourg":              "Europe/Luxembourg",
    "Malaysia":                "Asia/Kuala_Lumpur",
    "Mexico":                  "America/Mexico_City",
    "Moldova":                 "Europe/Chisinau",
    "Mongolia":                "Asia/Ulaanbaatar",
    "Morocco":                 "Africa/Casablanca",
    "Myanmar":                 "Asia/Rangoon",
    "Nepal":                   "Asia/Kathmandu",
    "Netherlands":             "Europe/Amsterdam",
    "New Zealand":             "Pacific/Auckland",
    "Nicaragua":               "America/Managua",
    "Nigeria":                 "Africa/Lagos",
    "North Korea":             "Asia/Pyongyang",
    "Norway":                  "Europe/Oslo",
    "Oman":                    "Asia/Muscat",
    "Pakistan":                "Asia/Karachi",
    "Palestine":               "Asia/Gaza",
    "Panama":                  "America/Panama",
    "Paraguay":                "America/Asuncion",
    "Peru":                    "America/Lima",
    "Philippines":             "Asia/Manila",
    "Poland":                  "Europe/Warsaw",
    "Portugal":                "Europe/Lisbon",
    "Qatar":                   "Asia/Qatar",
    "Romania":                 "Europe/Bucharest",
    "Russia":                  "Europe/Moscow",
    "Saudi Arabia":            "Asia/Riyadh",
    "Serbia":                  "Europe/Belgrade",
    "Singapore":               "Asia/Singapore",
    "Slovakia":                "Europe/Bratislava",
    "Slovenia":                "Europe/Ljubljana",
    "South Africa":            "Africa/Johannesburg",
    "South Korea":             "Asia/Seoul",
    "Spain":                   "Europe/Madrid",
    "Sri Lanka":               "Asia/Colombo",
    "Sudan":                   "Africa/Khartoum",
    "Sweden":                  "Europe/Stockholm",
    "Switzerland":             "Europe/Zurich",
    "Syria":                   "Asia/Damascus",
    "Taiwan":                  "Asia/Taipei",
    "Tajikistan":              "Asia/Dushanbe",
    "Tanzania":                "Africa/Dar_es_Salaam",
    "Thailand":                "Asia/Bangkok",
    "Tunisia":                 "Africa/Tunis",
    "Turkey":                  "Europe/Istanbul",
    "Turkmenistan":            "Asia/Ashgabat",
    "Uganda":                  "Africa/Kampala",
    "Ukraine":                 "Europe/Kiev",
    "United Arab Emirates":    "Asia/Dubai",
    "UAE":                     "Asia/Dubai",
    "United Kingdom":          "Europe/London",
    "UK":                      "Europe/London",
    "United States":           "America/New_York",
    "USA":                     "America/New_York",
    "Uruguay":                 "America/Montevideo",
    "Uzbekistan":              "Asia/Tashkent",
    "Venezuela":               "America/Caracas",
    "Vietnam":                 "Asia/Ho_Chi_Minh",
    "Yemen":                   "Asia/Aden",
    "Zimbabwe":                "Africa/Harare",


    "Alabama":         "America/Chicago",
    "Alaska":          "America/Anchorage",
    "Arizona":         "America/Phoenix",
    "Arkansas":        "America/Chicago",
    "California":      "America/Los_Angeles",
    "Colorado":        "America/Denver",
    "Connecticut":     "America/New_York",
    "Delaware":        "America/New_York",
    "Florida":         "America/New_York",
    "Georgia":         "America/New_York",
    "Hawaii":          "Pacific/Honolulu",
    "Idaho":           "America/Boise",
    "Illinois":        "America/Chicago",
    "Indiana":         "America/Indiana/Indianapolis",
    "Iowa":            "America/Chicago",
    "Kansas":          "America/Chicago",
    "Kentucky":        "America/Kentucky/Louisville",
    "Louisiana":       "America/Chicago",
    "Maine":           "America/New_York",
    "Maryland":        "America/New_York",
    "Massachusetts":   "America/New_York",
    "Michigan":        "America/Detroit",
    "Minnesota":       "America/Chicago",
    "Mississippi":     "America/Chicago",
    "Missouri":        "America/Chicago",
    "Montana":         "America/Denver",
    "Nebraska":        "America/Chicago",
    "Nevada":          "America/Los_Angeles",
    "New Hampshire":   "America/New_York",
    "New Jersey":      "America/New_York",
    "New Mexico":      "America/Denver",
    "New York":        "America/New_York",
    "North Carolina":  "America/New_York",
    "North Dakota":    "America/Chicago",
    "Ohio":            "America/New_York",
    "Oklahoma":        "America/Chicago",
    "Oregon":          "America/Los_Angeles",
    "Pennsylvania":    "America/New_York",
    "Rhode Island":    "America/New_York",
    "South Carolina":  "America/New_York",
    "South Dakota":    "America/Chicago",
    "Tennessee":       "America/Chicago",
    "Texas":           "America/Chicago",
    "Utah":            "America/Denver",
    "Vermont":         "America/New_York",
    "Virginia":        "America/New_York",
    "Washington":      "America/Los_Angeles",
    "West Virginia":   "America/New_York",
    "Wisconsin":       "America/Chicago",
    "Wyoming":         "America/Denver",

    # --- Major cities / regions ---
    "London":          "Europe/London",
    "Paris":           "Europe/Paris",
    "Berlin":          "Europe/Berlin",
    "Madrid":          "Europe/Madrid",
    "Rome":            "Europe/Rome",
    "Amsterdam":       "Europe/Amsterdam",
    "Brussels":        "Europe/Brussels",
    "Zurich":          "Europe/Zurich",
    "Vienna":          "Europe/Vienna",
    "Stockholm":       "Europe/Stockholm",
    "Oslo":            "Europe/Oslo",
    "Copenhagen":      "Europe/Copenhagen",
    "Helsinki":        "Europe/Helsinki",
    "Warsaw":          "Europe/Warsaw",
    "Prague":          "Europe/Prague",
    "Budapest":        "Europe/Budapest",
    "Bucharest":       "Europe/Bucharest",
    "Athens":          "Europe/Athens",
    "Istanbul":        "Europe/Istanbul",
    "Moscow":          "Europe/Moscow",
    "Dubai":           "Asia/Dubai",
    "Riyadh":          "Asia/Riyadh",
    "Tehran":          "Asia/Tehran",
    "Karachi":         "Asia/Karachi",
    "Mumbai":          "Asia/Kolkata",
    "Delhi":           "Asia/Kolkata",
    "Kolkata":         "Asia/Kolkata",
    "Dhaka":           "Asia/Dhaka",
    "Colombo":         "Asia/Colombo",
    "Kathmandu":       "Asia/Kathmandu",
    "Bangkok":         "Asia/Bangkok",
    "Jakarta":         "Asia/Jakarta",
    "Singapore":       "Asia/Singapore",
    "Kuala Lumpur":    "Asia/Kuala_Lumpur",
    "Hong Kong":       "Asia/Hong_Kong",
    "Shanghai":        "Asia/Shanghai",
    "Beijing":         "Asia/Shanghai",
    "Tokyo":           "Asia/Tokyo",
    "Seoul":           "Asia/Seoul",
    "Sydney":          "Australia/Sydney",
    "Melbourne":       "Australia/Melbourne",
    "Brisbane":        "Australia/Brisbane",
    "Perth":           "Australia/Perth",
    "Adelaide":        "Australia/Adelaide",
    "Auckland":        "Pacific/Auckland",
    "New Zealand":     "Pacific/Auckland",
    "Fiji":            "Pacific/Fiji",
    "Papua New Guinea":"Pacific/Port_Moresby",

    # --- Atlantic / Other ---
    "Azores":          "Atlantic/Azores",
    "Bermuda":         "Atlantic/Bermuda",
    "Cape Verde":      "Atlantic/Cape_Verde",
    "Greenland":       "America/Nuuk",
}

now = datetime.datetime.now

def abbr(zone):
    try:
        return now(zoneinfo.ZoneInfo(zone)).strftime("%Z")
    except Exception:
        return "???"

def offset_seconds(zone):
    try:
        dt = now(zoneinfo.ZoneInfo(zone))
        return int(dt.utcoffset().total_seconds())
    except Exception:
        return 0

lines = []

# Aliases first, sorted by display name.
for name in sorted(ALIASES):
    zone = ALIASES[name]
    lines.append(f"{name}  [{abbr(zone)}]  →  {zone}  @@{offset_seconds(zone)}")

# Raw IANA zones after.
zoneinfo_root = pathlib.Path("/usr/share/zoneinfo")
skip = {"posix", "right"}
raw_zones = sorted(
    str(p.relative_to(zoneinfo_root))
    for p in zoneinfo_root.rglob("*")
    if p.is_file() and p.parts[len(zoneinfo_root.parts)] not in skip
    and len(p.relative_to(zoneinfo_root).parts) >= 2
)
for zone in raw_zones:
    lines.append(f"{zone}  [{abbr(zone)}]  @@{offset_seconds(zone)}")

print("\n".join(lines))
