# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="{background}"
# Main text color
theme[main_fg]="{foreground}"
# Title color for boxes
theme[title]="{color1}"
# Highlight color for keyboard shortcuts
theme[hi_fg]="{color2}"
# Background color of selected items
theme[selected_bg]="{color8}"
# Foreground color of selected items
theme[selected_fg]="{color7}"
# Color of inactive/disabled text
theme[inactive_fg]="{color8}"
# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="{color7}"
# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="{color10}"
# Cpu box outline color
theme[cpu_box]="{color4}"
# Memory/disks box outline color
theme[mem_box]="{color5}"
# Net up/down box outline color
theme[net_box]="{color6}"
# Processes box outline color
theme[proc_box]="{color3}"
# Box divider line and small boxes line color
theme[div_line]="{color8}"
# Temperature graph colors
theme[temp_start]="{color2}"
theme[temp_mid]="{color3}"
theme[temp_end]="{color1}"
# CPU graph colors
theme[cpu_start]="{color4}"
theme[cpu_mid]="{color3}"
theme[cpu_end]="{color1}"
# Mem/Disk free meter
theme[free_start]="{color1}"
theme[free_mid]="{color3}"
theme[free_end]="{color2}"
# Mem/Disk cached meter
theme[cached_start]="{color4}"
theme[cached_mid]="{color12}"
theme[cached_end]="{color6}"
# Mem/Disk available meter
theme[available_start]="{color1}"
theme[available_mid]="{color5}"
theme[available_end]="{color3}"
# Mem/Disk used meter
theme[used_start]="{color2}"
theme[used_mid]="{color3}"
theme[used_end]="{color1}"
# Download graph colors
theme[download_start]="{color2}"
theme[download_mid]="{color10}"
theme[download_end]="{color6}"
# Upload graph colors
theme[upload_start]="{color1}"
theme[upload_mid]="{color9}"
theme[upload_end]="{color5}"
# Process box color gradient for threads, mem and cpu usage
theme[process_start]="{color4}"
theme[process_mid]="{color3}"
theme[process_end]="{color1}"
