title=terminal

# Font and Padding

font=terminus-font:size=14
pad=5x5 center-when-maximized-and-fullscreen

# Cursor Configuration

[cursor]
style=beam
beam-thickness=1.5

# Keybindings

[key-bindings]
 scrollback-up-line=Alt+k
 scrollback-down-page=Alt+j
 clipboard-copy=Alt+c XF86Copy
 clipboard-paste=Alt+v XF86Paste
 font-increase=Alt+Shift+k Control+KP_Add
 font-decrease=Alt+Shift+j Control+KP_Subtract

# Pywal Colourscheme

[colors-dark]
background={color0.strip}
foreground={color7.strip}
regular0={color0.strip}
regular1={color1.strip}
regular2={color2.strip}
regular3={color3.strip}
regular4={color4.strip}
regular5={color5.strip}
regular6={color6.strip}
regular7={color7.strip}
bright0={color8.strip}
bright1={color1.strip}
bright2={color2.strip}
bright3={color3.strip}
bright4={color4.strip}
bright5={color5.strip}
bright6={color6.strip}
bright7={color7.strip}
alpha=0.8

# Tweaks

[tweak]
font-monospace-warn=no
grapheme-shaping=yes
